# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "alvistack/ubuntu-24.04"

  # SonarQube VM
  config.vm.define "sonar-server" do |node|
    node.vm.hostname = "sonar-server"
    node.vm.network "private_network", ip: "192.168.56.52"

    node.vm.provider "libvirt" do |lv|
      lv.memory = 4096   # SonarQube needs RAM; bump to 6144/8192 if you can
      lv.cpus   = 2
    end
  end
end

